alias ls="ls -Fl --color"
alias lsa="ls -aFl --color"
alias tl="tree -L"

# git
alias gd="git diff"
alias gs="git status"
alias gau="git add -u"
alias gbd="git branch -D"
alias gcm="git commit"
alias gco="git checkout"
alias gds="git diff --staged"
alias glg="git log --graph"
alias gpf="git push --force"
alias gpl="git pull"
alias gpr="git pull --rebase"
alias gps="git push"
alias gri="EDITOR=emacs git rebase -i"
alias gcma="git commit --amend"
alias gcob="git checkout -b"
alias gcmmsg="git commit -m"
