alias ls="ls -aFl --color"
alias tl="tree -L"

# emacs
alias enw="emacs -nw --no-site-file --no-site-lisp --no-splash --no-x-resources"
alias emc="emacsclient -t"

# git
alias gd="git diff"
alias gs="git status"
alias gau="git add -u"
alias gbd="git branch -D"
alias gcm="EDITOR=emacs git commit"
alias gco="git checkout"
alias gds="git diff --staged"
alias glg="git log --graph"
alias gri="EDITOR=emacs git rebase -i"
alias gcma="git commit --amend"
alias gpfo="git push --force origin"
alias gcob="git checkout -b"
alias gpom="git pull origin master"
alias gpos="git pull origin staging"
alias gprom="git pull --rebase origin master"
alias gpros="git pull --rebase origin staging"
alias gcmmsg="git commit -m"
